#!/bin/bash

#Specify some options for QSUB
#$ -V -j y -R y

# Specify which queue
#$ -q phys-lab

# Execute script from current working directory
#$ -cwd
# Select max run-time (3 hours)
#$ -l h_rt=03:00:00

#$ -t 1-128  
echo "Task ID is $SGE_TASK_ID"

# Load the FORTRAN and Python (Miniconda) modules
module load Anaconda3/4.3.1 
module load openmpi

#set job running
./Shell/ddpt-process-parallel.sh $SGE_TASK_ID
